### ISSUE TITLE
ConcatPDF : incomptability with v17 document public signature interface

### ISSUE THREAD

**Issue by marc-dll** [DoliCloud/DoliMods#24]
Dolibarr v17 permits sharing a public link to add a signature to documents like proposals. When using this feature in conjuction with ConcatPDF, the signature is added in the last page of the concatenated PDFs instead of the last page of the original PDF.

**Comment by atm-quentin** [comment]
Hi everyone,

Just following up on an issue reported about a year ago concerning public signature links when using ConcatPDF.

I can confirm this bug is still present in v20. The signature is placed on the last page of the final concatenated PDF, instead of the last page of the original document (e.g., the proposal).

This significantly impacts the usability of this feature when additional documents are attached.

Hoping this can be addressed soon.

Thanks. @eldy

**Comment by eldy** [comment]
I think this has been fixed with v22.

**Comment by atm-quentin** [comment]
Thanks for the update! It's great to hear this has been addressed in v22.

Since many users are still on older versions (like v20/v21) where this bug prevents proper use of online signatures with attached documents, would it be possible to backport this fix?

It would be really helpful. Would you be able to look into handling the backport, perhaps to ensure your module's compatibility with online signatures on these versions?

Thanks again for your work on this.

**Comment by atm-maxime** [comment]
@atm-quentin I tried on my own and it worked for me. We'll check together

**Comment by ramonetroca** [comment]
Hello, the bug still present on v. 22.0.2
Any news about this?
@atm-maxime it works for you in what version?
Thank's
